### ISSUE TITLE
Link not marked

### ISSUE THREAD

**Issue by babacarcissedia** [kfirba/Mavigator#3]
First of all, I want to say that it's a good thing you thought about writing a decent class because I always write again the same code for every project.
Anyway, I tried it, but no results. Waiting to see what is the problem
![mavigator](https://cloud.githubusercontent.com/assets/17571380/20856923/0e2267e8-b915-11e6-9e58-b2b479935298.png)
![mavigator](https://cloud.githubusercontent.com/assets/17571380/20856931/57591790-b915-11e6-9064-a377bd41f2c6.png)
![mavigator](https://cloud.githubusercontent.com/assets/17571380/20856944/8cfef55e-b915-11e6-8226-3195511fdd58.png)

**Comment by kfirba** [comment]
@bcdbuddy Hey!

I think the issue is with your first argument. The first argument (`"a"` in your case) is the container to look for links in.

When you specify the selector of `"a"` it will try to find inside all `<a>` tags a link to mark.

Try to do the following:

```js
Mavigator.mark('.blog-nav');
```

You don't have to pass the options as I see they are identical to the defaults one.

Let me know if it helped you :)!

**Comment by babacarcissedia** [comment]
It's working fine now! Here is what I did
![cap](https://cloud.githubusercontent.com/assets/17571380/20871139/02db3dc6-ba8a-11e6-8ee1-7ce6059898b1.png)

Thanks again for sharing. It keeps me from doing the same job again.
